_target_: src.policies.ICRLSACPolicy
actor:
  _target_: "src.utils.net.continuous.ActorProb" 
  preprocess_net:
    _target_: "tianshou.utils.net.common.Net"
    hidden_sizes: [256,256]
  unbounded: True
  conditioned_sigma: True
critics:
    - 
      _target_: "src.utils.net.continuous.DoubleCritic"
      preprocess_net1:
        _target_: "tianshou.utils.net.common.Net"
        hidden_sizes: [256,256]
        concat: True
      preprocess_net2:
        _target_: "tianshou.utils.net.common.Net"
        hidden_sizes: [256,256]
        concat: True
    - 
      _target_: "src.utils.net.continuous.DoubleCritic"
      preprocess_net1:
        _target_: "tianshou.utils.net.common.Net"
        hidden_sizes: [256,256]
        concat: True
      preprocess_net2:
        _target_: "tianshou.utils.net.common.Net"
        hidden_sizes: [256,256]
        concat: True
actor_optim:
  _target_: "torch.optim.Adam"
  lr: 0.001
critic_optim:
  _target_: "torch.optim.Adam"
  lr: 0.001
tau: 0.005
gamma: 0.99
# alpha: 0.2
n_step: 1
use_lagrangian: True
rescaling: false
lagrangian: 1
cost_limit: 0.01
alpha:
  optim:
    _target_: "torch.optim.Adam"
    lr: 0.0003
normalize_reward: False
