# @package _global_

task: "HalfCheetahWall-v0"
expert_data_path: "data/icrl/half_cheetah"
cost_fn: 
  _target_: src.utils.cost_functions.wall_behind
  pos: -3
trainer:
  update_per_step: 0.005
  max_epoch: 30
  batch_size: 64
reward:
  optim:
    lr: 0.05
  net:
    preprocess_net:
      hidden_sizes: [20]
  steps_per_epoch: 250
policy:
  actor:
    preprocess_net:
      hidden_sizes: [64,64]
  critic:
    preprocess_net:
      hidden_sizes: [64,64]
  actor_optim:
    lr: 0.0003
  critic_optim:
    lr: 0.0003
