# @package _global_

task: "HalfCheetah-v4"
expert_data_path: "data/d4rl/halfcheetah_expert-v2.hdf5"
data:
  _target_: src.data.readers.D4RLReader
  num_episodes: 50
cost_fn: 
  _target_: src.utils.cost_functions.zero
reward:
  optim:
    lr: 0.0001
  net:
    preprocess_net:
      hidden_sizes: [64, 64]
  steps_per_epoch: 1

