# @package _global_

task: "HalfCheetah-v4"
expert_data_path: Null
data:
  _target_: src.data.readers.DummyReader
cost_fn: 
  _target_: src.utils.cost_functions.zero
reward:
  optim:
    lr: 0.0001
  net:
    preprocess_net:
      hidden_sizes: [64, 64]
  steps_per_epoch: 1
