# @package _global_

task: "HalfCheetahWall-v0"
expert_data_path: "data/icrl/half_cheetah"
cost_fn: 
  _target_: src.utils.cost_functions.wall_behind
  pos: -3
reward:
  optim:
    lr: 0.0001
  net:
    preprocess_net:
      hidden_sizes: [64, 64]
  steps_per_epoch: 1
