# @package _global_

task: "SwimmerWall-v0"
expert_data_path: "data/icrl/swimmer"
cost_fn: 
  _target_: src.utils.cost_functions.wall_infront
  pos: 0.5
reward:
  optim:
    lr: 0.0001
  net:
    preprocess_net:
      hidden_sizes: [64, 64]
  steps_per_epoch: 1



