# @package _global_

task: "SwimmerWall-v0"
expert_data_path: "data/icrl/swimmer"
cost_fn: 
  _target_: src.utils.cost_functions.wall_infront
  pos: 0.5
trainer:
  update_per_step: 0.01
  max_epoch: 100
  step_per_epoch: 50000
reward:
  optim:
    lr: 0.001
  net:
    preprocess_net:
      hidden_sizes: [20]
  steps_per_epoch: 5
policy:
  actor:
    preprocess_net:
      hidden_sizes: [64,64]
  critic:
    preprocess_net:
      hidden_sizes: [64,64]
  actor_optim:
    lr: 0.0003
  critic_optim:
    lr: 0.0003


