defaults:
  - policy: irl_sac
  - reward: linear_mlp
  - trainer: off_policy
  - data: d4rl
  - logger: wandb
task: "HalfCheetah-v4"
train_env_num: 1
test_env_num: 1
train_buffer_size: 1000000
test_buffer_size: 10000
warmstart_timesteps: 1000
seed: 0
expert_data_path: "data/halfcheetah_expert-v2.hdf5"
logger:
  name: ${task}-${seed}
  project: single-task-irl
log_path: wandb/${now:%Y-%m-%d}_${now:%H-%M-%S}
device: cuda
  