defaults:
  - policy: sac_lag
  - collector: fsrl
  - trainer: safe_off_policy
  - data: icrl
  - logger: fsrl_wandb
  - env: inverted_pendulum
train_env_num: 1
test_env_num: 5
train_buffer_size: 1000000
test_buffer_size: 10000
warmstart_episodes: 10
cost_limit: 0.1
seed: 0
logger:
  name: Safety-Expert-${task}-${seed}
  project: single-task-icl
log_path: wandb/${now:%Y-%m-%d}_${now:%H-%M-%S}
device: cuda
  