_target_: "src.rewards.reward_learner.RewardLearner"
steps_per_epoch: 1
batch_size: 5000
regularization_coeff: 0
regularization_type: "l1"
learn_true_rewards: false
net:
  _target_: "src.utils.net.continuous.Reward"
  preprocess_net:
    _target_: "tianshou.utils.net.common.Net"
    hidden_sizes: [64,64]
    concat: True
  clip_range: [-20, 0]
  output_transform: null
optim:
  _target_: "torch.optim.Adam"
  lr: 0.02
  weight_decay: 0.001
lr_scheduler: null
is_constraint: false
loss_transform: null